import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import { execSync } from 'child_process'
import chalk from 'chalk'
import * as manifest from '../../lib/manifest.js'
import { detect } from '../../lib/runtime.js'

export function graphInit(): void {
  const root = process.cwd()

  if (!manifest.exists(root)) {
    console.error(chalk.red('No space.manifest.json found in current directory'))
    console.log(chalk.dim('  Run this command inside a Construct space project.'))
    process.exit(1)
  }

  const m = manifest.read(root)

  // Create models directory
  const modelsDir = join(root, 'src', 'models')
  mkdirSync(modelsDir, { recursive: true })

  // Create index.ts barrel file
  const indexPath = join(modelsDir, 'index.ts')
  if (!existsSync(indexPath)) {
    writeFileSync(indexPath, `// Data models for ${m.name}\n// Generated by construct graph init\n\n// Export your models here:\n// export { User } from './User'\n`)
  }

  // Add @construct-space/graph dependency
  const pkgPath = join(root, 'package.json')
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'))
  if (!pkg.dependencies) pkg.dependencies = {}

  if (!pkg.dependencies['@construct-space/graph']) {
    // Get latest version
    let version = '0.1.0'
    try {
      version = execSync('npm view @construct-space/graph version', { encoding: 'utf-8' }).trim()
    } catch {}

    pkg.dependencies['@construct-space/graph'] = `^${version}`
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')
    console.log(chalk.blue(`Added @construct-space/graph@^${version} to dependencies`))
  } else {
    console.log(chalk.dim('  @construct-space/graph already in dependencies'))
  }

  // Install dependencies
  const rt = detect()
  console.log(chalk.dim(`  Installing dependencies with ${rt.name}...`))
  execSync(rt.name === 'bun' ? 'bun install' : 'npm install', { cwd: root, stdio: 'inherit' })

  console.log()
  console.log(chalk.green('Graph initialized!'))
  console.log()
  console.log('  Generate a model:')
  console.log(chalk.cyan('  construct graph g User name:string email:string active:boolean'))
  console.log()
  console.log('  Push models to Graph:')
  console.log(chalk.cyan('  construct graph push'))
  console.log()
}
