#!/usr/bin/env bun
/**
 * Reads all files from templates/space/ and writes src/lib/embedded-templates.ts.
 * This is run before every build so the compiled binary has templates inlined.
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'fs'
import { join, relative } from 'path'

const root = join(import.meta.dir, '..')
const templatesDir = join(root, 'templates', 'space')
const outFile = join(root, 'src', 'lib', 'embedded-templates.ts')

function walk(dir: string): string[] {
  const results: string[] = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      results.push(...walk(full))
    } else {
      results.push(full)
    }
  }
  return results
}

const files = walk(templatesDir)
const entries: string[] = []

for (const file of files) {
  const key = relative(templatesDir, file)
  const content = readFileSync(file, 'utf-8')
  const escaped = JSON.stringify(content)
  entries.push(`  ${JSON.stringify(key)}: ${escaped}`)
}

const output = `// AUTO-GENERATED by scripts/embed-templates.ts — DO NOT EDIT
export const EMBEDDED_TEMPLATES: Record<string, string> = {
${entries.join(',\n')},
}
`

writeFileSync(outFile, output)
console.log(`Embedded ${files.length} templates → src/lib/embedded-templates.ts`)
